opts:
  # required args
  - name: dbname
    desc: "database to dump"
  - name: host
    desc: "database server host or socket directory"
  - name: port
    desc: "database server port number"
  - name: username
    short: U
    desc: "connect as specified database user"
  - name: output
    short: O
    desc: "output path"
  # optional args
  - name: schema
    type: list
    short: "n"
    desc: "dump only schemas matching pattern"
    optional: true
  - name: exclude-schema
    type: list
    short: "N"
    desc: "do not dump any schemas matching pattern"
    optional: true
  - name: verbose
    defaultValue: "true"
    type: bool
    optional: true
  - name: jobs
    defaultValue: "2"
    optional: true
